### ISSUE TITLE
Please add a licence (MIT,GNU?)

### ISSUE THREAD

**Issue by 3fon3fonov** [Axel-Erfurt/PyEdit2#1]
Dear Axel,

I like your PyEdit2! I was looking for a compact python highlight code for my project:

https://github.com/3fon3fonov/trifon

Actually, I only aim to use your syntax_py.py, since I only want a basic text editor with some highlight possibilities for python. 

Currently, I am using:
https://github.com/mfitzp/15-minute-apps/tree/master/wordprocessor
  
and I "hacked it" as I included:

from syntax_py import Highlighter

and later:      

self.highlighter = Highlighter(document)

and it works!

However, please add a Licence, so I can use it too (of course PyEdit2 will get all the credits).

![example](https://user-images.githubusercontent.com/44244057/67437539-5f853680-f5f1-11e9-9c9c-6aec52eb787a.png)

**Comment by 3fon3fonov** [comment]
BTW,  "syntax_py.py" has a small bug.

You forgot to close the triple quote comment in line 163

**Comment by Axel-Erfurt** [comment]
Thanks for the hint.

added license.

The  triple quote comment in line 163 was for closing  the comment above.

Maybe there is an error in using triple quotes multiple times.

I changed it now, let's see if it works.

instead of `"""`
I use now
"% s% s% s" % (chr (34), chr (34), chr (34))
